apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: nwthelm11        
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.TargetPort }}
      NodePort:  {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: nwthelm11
